### PR TITLE
CLI support, CLI tests

### PR DESCRIPTION
**Pull request by tunnckoCore**
More info [CLI in readme](https://github.com/jonschlinkert/strip-comments/tree/cli#cli)

@jonschlinkert @niksy thoughts?

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Hm. I'll come to this these days. I should move to `minimist` instead of commander, @jonschlinkert what you think? I also should make command again to be `strip-comments`.

**Comment by jonschlinkert** [comment]
wow I forgot all about this. yeah I'm good with both of those suggestions. thanks

**Comment by tunnckoCore** [comment]
> wow I forgot all about this.

same here, lol. the todo cycle ...

**Comment by jonschlinkert** [comment]
closing since this has been refactored. I'd be open to this still if it was done with no deps. thanks for the pr, I do appreciate it

**Pull request closed without merging**
