### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by Jameskmonger**
This will significantly reduce the size of the npm distribution.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
hi @Jameskmonger. I no longer use `.npmignore` since npm now supports the [files property](https://docs.npmjs.com/files/package.json#files) in package.json, which allows you to specify [only the files you wish to include](https://github.com/jonschlinkert/strip-comments/blob/master/package.json#L13). It's easier to maintain and results in fewer files in the repository root. 

I do appreciate the pr though, thank you

**Comment by Jameskmonger** [comment]
No problem @jonschlinkert - I hadn't noticed that you were using the `files` property. It's much easier to maintain!

**Comment by tunnckoCore** [comment]
And as I know npmignore inherits gitignore, i think it works this even in npm@1 or npm@2

**Comment by Jameskmonger** [comment]
I know that gitignore is used if there is no npmignore file, but I'm not sure on the behaviour if there is both a `.npmignore` and a `.gitignore` file @tunnckoCore

**Pull request closed without merging**
